sudo: false
language: node_js
node_js:
- '6.6.0'
after_install:
- npm dedupe
- npm shrinkwrap --dev
- cat npm-shrinkwrap.json
script:
- npm run dist
after_success:
- '[ $TRAVIS_BRANCH == master ] && surge --project ./dist --domain builder.prototypo.io'
- '[ $TRAVIS_BRANCH == develop ] && surge --project ./dist --domain builder-dev.prototypo.io'
branches:
  only:
    - master
    - develop
